include:
    -   template: Jobs/Secret-Detection.gitlab-ci.yml

stages:
    - test
    - announce

.test_job: &test_job
    stage: test
    before_script:
        - composer install --no-interaction --prefer-dist --no-progress
    script:
        - vendor/bin/phpcs src/ tests/
        - vendor/bin/phpunit
    cache:
        paths:
            - vendor/
    rules:
        - if: $CI_COMMIT_BRANCH

test:php8.1:
    <<: *test_job
    image: nexendrie/php:8.1

test:php8.2:
    <<: *test_job
    image: nexendrie/php:8.2

test:php8.3:
    <<: *test_job
    image: nexendrie/php:8.3

test:php8.4:
    <<: *test_job
    image: nexendrie/php:8.4

test:reports:
    extends:
        - .test_job
    image: nexendrie/php:8.4
    script:
        - vendor/bin/phpunit --coverage-text --coverage-filter src --colors=never --log-junit junit.xml
        - vendor/bin/phpstan analyze --error-format=gitlab | tee phpstan.json
    coverage: '/^\s*Lines:\s*\d+.\d+\%/'
    artifacts:
        paths:
            - junit.xml
            - phpstan.json
        reports:
            junit: junit.xml
            codequality: phpstan.json

announce:gitlab:
    stage: announce
    image: registry.gitlab.com/gitlab-org/release-cli:latest
    rules:
        - if: $CI_COMMIT_TAG
    script:
        - echo "Creating GitLab release"
    release:
        tag_name: $CI_COMMIT_TAG
        name: "Rest Route $CI_COMMIT_TAG"
        description: "./RELEASE_NOTES"
