name: Tests

on:
    push:
        branches:
            - '*'

jobs:
    tests:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                php:
                    - '8.1'
                    - '8.2'
                    - '8.3'
                    - '8.4'
                os:
                    - ubuntu-latest
                    - windows-latest
        steps:
            - uses: actions/checkout@v4
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  tools: composer, phing
                  coverage: pcov
            - run: composer update --prefer-dist --no-progress --no-interaction
            - run: vendor/bin/phpcs src/ tests/
            - run: vendor/bin/phpunit
